package ninja.samryecroft.returnhome.tracker.document;

import java.util.Map;

/**
 * Durable object storage for already-encrypted document bytes.
 *
 * <p>Implementations are deliberately <strong>crypto-unaware</strong>: they move opaque bytes and a
 * small string map, and know nothing about organisations, keys or reports. Everything handed here
 * is already ciphertext, which is what lets the same envelope travel unchanged between the local
 * filesystem, Azurite and Azure Blob.
 *
 * <p>The metadata map models Azure blob metadata, so implementations must survive its rules: names
 * are case-insensitive C#-identifier-ish, values are ASCII header values. {@link DocumentEnvelope}
 * is the only producer of these maps and already encodes to base64 for that reason.
 */
public interface StorageProvider {

    /**
     * Writes (or overwrites) an object. Keys are always server-generated by
     * {@link EncryptedReportStore}; implementations still validate them, because the key round-trips
     * through the database and validating at the boundary is cheaper than trusting the round trip.
     */
    void put(String key, byte[] content, Map<String, String> metadata);

    /** @throws DocumentNotFoundException if no object exists under this key */
    StoredObject get(String key);

    boolean exists(String key);

    /** A short name for this backend, used in logs and audit metadata (e.g. {@code "local"}). */
    String describe();
}
