package ninja.samryecroft.returnhome.tracker.export;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.List;
import ninja.samryecroft.returnhome.tracker.audit.AuditHistoryEntry;
import ninja.samryecroft.returnhome.tracker.audit.AuditHistorySection;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.stereotype.Component;

/**
 * Renders the cover sheet and case narrative that lead the pack.
 *
 * <p>The cover sheet is the most important page in this product that is not a screen. It is what an
 * inspector reads first and what someone re-sending the pack forwards without opening anything else,
 * so it has to answer - unprompted - what this is, who produced it, why, what it covers, and
 * <em>what it does not contain</em>.
 *
 * <p><strong>Every line here is rendered from {@link AuditHistoryEntry}, never from a raw audit
 * row.</strong> That projection holds the per-event-type allow-list that keeps free-text fields - a
 * filename, an access-denied reason, a review comment - out of what gets rendered. Reaching past it
 * would re-open exactly the hole it was built to close, in the one artefact that then leaves the
 * building and cannot be recalled. If something cannot be said from the projection, the answer is to
 * extend the projection, not to reach around it.
 */
@Component
public class CaseFileNarrativeWriter {

    private static final PDType1Font BODY = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
    private static final PDType1Font BOLD = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
    private static final float MARGIN = 56f;
    private static final float LEADING = 15f;

    public byte[] write(ExportPackWriter.PackRequest request) {
        try (PDDocument document = new PDDocument(); ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Cursor cursor = new Cursor(document);

            cursor.heading("Return home interview — case file");
            cursor.gap();
            cursor.field("Subject", request.childReference());
            cursor.field("Period covered", request.manifest().periodLabel());
            cursor.field("Purpose", request.purpose().getLabel());
            if (request.reference() != null && !request.reference().isBlank()) {
                cursor.field("Reference", request.reference());
            }
            cursor.field("Generated by", request.generatedBy());
            cursor.field("Generated at", ExportPackWriter.formatStamp(request.generatedAt()));
            cursor.field("Interviews included", Integer.toString(request.manifest().includedCount()));
            cursor.field("Reports attached", Integer.toString(request.manifest().documentCount()));

            if (request.manifest().partialScope()) {
                cursor.gap();
                cursor.subheading("This pack is partial");
                cursor.paragraph(request.manifest().partialScopeNote());
            }

            // Exclusions sit on the cover sheet, above the narrative, and not in an appendix. An
            // inspector who finds a missing episode later concludes the system hides things; saying
            // so here, with the reason, turns a gap into evidence of completeness.
            cursor.gap();
            cursor.subheading("What is not in this pack");
            if (request.manifest().excluded().isEmpty()) {
                cursor.paragraph("Nothing has been excluded. Every interview in the period above is "
                        + "included, with its approved report attached.");
            } else {
                for (ExportManifest.ManifestEntry entry : request.manifest().excluded()) {
                    cursor.bullet(entry.label() + " — " + entry.reason());
                }
            }
            cursor.gap();
            cursor.paragraph("Sign-in and account activity are not included in this pack.");

            if (!request.attachments().isEmpty()) {
                cursor.gap();
                cursor.subheading("Attached documents");
                cursor.paragraph("Each report is the document as originally issued. It has not been "
                        + "regenerated, so it is byte-for-byte what was sent at the time. The checksum "
                        + "beside each one verifies that.");
                for (ExportPackWriter.AttachedReport attachment : request.attachments()) {
                    cursor.bullet(attachment.entryName());
                    cursor.mono("SHA-256 " + ExportPackWriter.sha256(attachment.content()));
                }
            }

            cursor.gap();
            cursor.paragraph("This export is recorded in the system's audit trail and can be verified "
                    + "against it. Producing this pack again creates a separate record.");

            writeHistory(cursor, request.history());

            cursor.close();
            document.save(out);
            return out.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to render the case file narrative", e);
        }
    }

    private void writeHistory(Cursor cursor, List<AuditHistorySection> history) throws IOException {
        cursor.newPage();
        cursor.heading("Case history");
        cursor.paragraph("The record of what happened and when, as held in this system. Roles are "
                + "shown rather than individual names.");
        if (history.isEmpty()) {
            cursor.gap();
            cursor.paragraph("No recorded activity falls within the period covered by this pack.");
            return;
        }
        for (AuditHistorySection section : history) {
            cursor.gap();
            cursor.subheading(section.label());
            for (AuditHistoryEntry entry : section.entries()) {
                cursor.bullet(entry.when() + "  —  " + entry.headline()
                        + (entry.actorRole() == null ? "" : "  (" + entry.actorRole() + ")"));
                if (entry.detail() != null && !entry.detail().isBlank()) {
                    cursor.mono(entry.detail());
                }
            }
        }
    }

    /** Minimal flowing-text cursor: PDFBox positions every string itself and will not paginate for us. */
    private static final class Cursor {

        private final PDDocument document;
        private PDPageContentStream stream;
        private float y;

        Cursor(PDDocument document) throws IOException {
            this.document = document;
            newPage();
        }

        void newPage() throws IOException {
            if (stream != null) {
                stream.close();
            }
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            stream = new PDPageContentStream(document, page);
            y = page.getMediaBox().getHeight() - MARGIN;
        }

        void heading(String text) throws IOException {
            write(text, BOLD, 16f, 0f);
            y -= 6f;
        }

        void subheading(String text) throws IOException {
            write(text, BOLD, 12f, 0f);
        }

        void field(String label, String value) throws IOException {
            write(label + ": " + value, BODY, 11f, 0f);
        }

        void paragraph(String text) throws IOException {
            write(text, BODY, 11f, 0f);
        }

        void bullet(String text) throws IOException {
            write("•  " + text, BODY, 11f, 0f);
        }

        void mono(String text) throws IOException {
            write(text, BODY, 9f, 16f);
        }

        void gap() {
            y -= LEADING * 0.6f;
        }

        private void write(String text, PDType1Font font, float size, float indent) throws IOException {
            float width = PDRectangle.A4.getWidth() - (MARGIN * 2) - indent;
            for (String line : wrap(text == null ? "" : text, font, size, width)) {
                if (y < MARGIN + LEADING) {
                    newPage();
                }
                stream.beginText();
                stream.setFont(font, size);
                stream.newLineAtOffset(MARGIN + indent, y);
                stream.showText(line);
                stream.endText();
                y -= LEADING;
            }
        }

        /**
         * PDFBox throws on characters the Standard 14 fonts cannot encode, and this text carries
         * em-dashes and curly quotes from real content - so unsupported characters are folded to
         * plain ASCII rather than allowed to fail a whole export at render time.
         */
        private List<String> wrap(String text, PDType1Font font, float size, float maxWidth) throws IOException {
            String safe = text.replace('—', '-').replace('–', '-')
                    .replace('‘', '\'').replace('’', '\'')
                    .replace('“', '"').replace('”', '"')
                    .replaceAll("[^\\x20-\\x7E]", "");
            List<String> lines = new ArrayList<>();
            StringBuilder line = new StringBuilder();
            for (String word : safe.split(" ")) {
                String candidate = line.isEmpty() ? word : line + " " + word;
                if (font.getStringWidth(candidate) / 1000 * size > maxWidth && !line.isEmpty()) {
                    lines.add(line.toString());
                    line = new StringBuilder(word);
                } else {
                    line = new StringBuilder(candidate);
                }
            }
            lines.add(line.toString());
            return lines;
        }

        void close() throws IOException {
            if (stream != null) {
                stream.close();
                stream = null;
            }
        }
    }
}
